### ISSUE TITLE
Prerequisites 

### ISSUE THREAD

**Issue by mcouplet** [be-oi/beoi-training#1]
I think we should have in each unit a file `prerequisites.md` indicating which units you should have already seen before you can dive into the topic. [I've done that for unit 13](https://github.com/be-oi/beoi-training/blob/master/units/13-dynamic-programming-i/prerequisites.md). What do you think of it? When all units will have its prerequisites, we can then build a graph and toposort it to know the best order we should teach the topics (assuming the graph is acyclic of course).

**Comment by vlecomte** [comment]
That sounds nice! I'm not sure if it's so essential for the trainers as they would hopefully have a feeling of the prerequisites of what they're teaching, but it will certainly help students who are going through the resources read them in a reasonable order. :)

**Comment by mcouplet** [comment]
I think it can also help trainers in that before lectures they can loop through the list and see if each contestant has already seen the prerequisites. E.g. in DP1 if you don't know about graphs it's no use attending the lecture.
